---
- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    max_clients: 5
  
  vars_prompt:
    - name: username
      prompt: What is your name?
  tasks:
  - name: Ensure Apache is  installed 
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"
 
  - name: Start Apache server
    service: name=httpd state=started
  
 # - name: Deploy configuration file
 #   template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
 #   notify:
 #     - Restart Apache  
  
  - name: create if it doesn't exist
    file:
      path: "{{ doc_root }}"
      state: directory

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html owner=root group=root mode=0644

  handlers:
     - name: Restart Apache
       service: name=httpd state=restarted

- hosts: dbservers
  sudo:  yes
 
  tasks:
  - name: Ensure MySQL is installed
    yum: name=mysql-server state=present
    when: ansible_os_family == "Debian"
  
  - name: Start MySQL
    service: name=mysqld state=started

